### ISSUE TITLE
Reward Timing

### ISSUE THREAD

**Issue by MickyHoltzman** [Anna4142/PrisonerDilemmaPy#32]
The values for the valve opening timings for the various rewards are hard coded in the SW, and (I think) in to places. One for the reward manager and the other for logging. The double SW definition is a recipe for disaster. Regardless, I believe these  numbers will continuously change because we will either need to tweak them to make the mouse learn or we would to know how changing them affect learning. Either way it sounds like a good idea to add them to the GUI. What do you think?

**Comment by Anna4142** [comment]
i did talk about it with nikol yesterday and i dont think it is something that should be added to the gui but it is something that depends on the total length of the experiment.That is because the mice can recieve a maximum amount of water in a certian day that is predetermined and we dont want to cross that threshold as we increase the experiment length.I think i will write a small script to dynamically asign the values depending on that days experiment length.

**Comment by MickyHoltzman** [comment]
OK. :-) I moved it to discussions,
